#!/bin/sh

case "$1" in
	start)
		echo "Starting wifibroadcast-g2g ..."
		wifibroadcast-g2g start
		;;

	stop)
		echo "Stopping wifibroadcast-g2g ..."
		wifibroadcast-g2g stop
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
